### ISSUE TITLE
Query parameter as an Array configuration

### ISSUE THREAD

**Issue by lngphp** [nelmio/NelmioApiDocBundle#1392]
In terms of Symfony 4, using `Swagger\Annotations`, how may I define a Parameter as an Array (`q[a]=1&q[b]=foo`)? I was doing it using Symfony 2 few years ago and cannot recall it nor find in Google... Please advice

**Comment by lngphp** [comment]
One week passed and nobody answered this question...

**Comment by GuilhemN** [comment]
See https://github.com/OAI/OpenAPI-Specification/issues/49#issuecomment-59009568, what you're looking for is `collectionFormat`.
As @goetas said please ask this kind of questions on dedicated channels, if you don't get an answer it's likely because people don't have time to do the research you could have done.

**Comment by spolischook** [comment]
see https://github.com/nelmio/NelmioApiDocBundle/issues/979#issuecomment-310899197
