### ISSUE TITLE
Pets?

### ISSUE THREAD

**Issue by BonBonSlick** [nelmio/NelmioApiDocBundle#1395]
Every time I run vendor/bin/swagger , I got pets in my json
```
{
    "swagger": "2.0",
    "info": {
        "title": "Swagger Petstore",
        "description": "This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "email": "apiteam@swagger.io"
        },
```
Like this

**Comment by scaytrase** [comment]
This bundle depends on https://github.com/zircote/swagger-php/tree/2.x which owns this binary, not this bundle

https://github.com/zircote/swagger-php/blob/2.x/bin/swagger

You can read command documentation to see you need specify directories to scan. Otherwise you'll get all the workspace scanned, including pet samples, yeah

https://github.com/zircote/swagger-php/blob/2.x/bin/swagger#L110

**Comment by GuilhemN** [comment]
@scaytrase explanation is perfect :+1:

**Comment by BonBonSlick** [comment]
@scaytrase  thank you
