### ISSUE TITLE
Support "allowReserved" for path parameters

### ISSUE THREAD

**Issue by leonboot** [nelmio/NelmioApiDocBundle#1474]
I've [raised an issue with the swagger-php package](https://github.com/zircote/swagger-php/issues/656) about providing support for the `allowReserved` flag for path parameters. When support is added for this flag, NelmioApiDocBundle should respect this flag and prevent certain characters from being urlencoded. Currently, if a slash is provided for a path parameter, this slash gets encoded and, especially when using Apache, the request fails.

**Comment by andrescevp** [comment]
I rased the same issue...

**Comment by GuilhemN** [comment]
The issue is you're refering to OpenApi version 3.
In order to use this feature you will have to upgrade to NelmioApiDocumentation v4 first (which is still in beta).

You may also check whether Swagger 2 does support this (see https://swagger.io/docs/specification/2-0/describing-parameters/) but at first sight it seems not.
