### ISSUE TITLE
Bad mapping with @var with annotation array @ORM\Column(type="array", nullable=true)

### ISSUE THREAD

**Issue by kevin-schmitt** [nelmio/NelmioApiDocBundle#1616]
Hello,

i get error when i use 

 ```
/**
     * @var string[]
     * @ORM\Column(type="array", nullable=true)
     */
    private $alerts;
```

But like this work
```
/**
     * @var string[]
     */
    private $alerts;
```
For fix this i have to use swagger property but i would like use @var is more simple. This feature exist?

**Comment by GuilhemN** [comment]
@FilipBenco submitted a fix in https://github.com/nelmio/NelmioApiDocBundle/pull/1639, however I believe this issue should be fixed in Symfony itself (see https://github.com/nelmio/NelmioApiDocBundle/pull/1639#issuecomment-636481509).

As a side note, your `@var` annotation is not compatible with doctrine type, it should probably be `@var string[]|null` :)

**Comment by chrisguitarguy** [comment]
Going to close this one due to age, also not sure if doctrine annotation reading is a thing anymore?
