### ISSUE TITLE
@NotBlank and allowNull=true

### ISSUE THREAD

**Issue by frostieDE** [nelmio/NelmioApiDocBundle#1647]
Symfony's `@NotBlank` constraint allows to specify whether or not `null` values are allowed (`@NotBlank(allowNull=true)`). See [Symfony docs](https://symfony.com/doc/current/reference/constraints/NotBlank.html#allownull).

Currently, the bundle displays all properties with this annotation as required, even with `allowNull` set to `true`. 

My proposal: In case of `allowNull=true`, the property should not be marked as required.

What do you think?

**Comment by GuilhemN** [comment]
Sure why not :) Would you like to submit a PR?

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1711 :)

**Comment by xrodet-wanadev** [comment]
Hi @frostieDE @GuilhemN,

Sorry to re-open this old issue, but I really disagree with this PR.

If you want a **_non required nullable field_**, all you to have to is **NOT TO USE** the `NotBlank` annotation !

In my case I need the opposite: a **_required nullable field_** and I have **NO WAY** to achieve that because of this PR (I though `@NotBlank(allowNull=true)` will do the job, but because of this PR it doesn't works obviously)

You might ask, why do I want to achieve that ?

In my API I am using a PUT request to update my resources, in REST API the PUT request is designed to update the whole resource, so I need all the fields to be required (even the nullable ones).

Why ? because if you don't do this, the missing nullable field in the payload will be set to the default value (null) and then erase the old resource value implicitly... which is very vey bad :-(

What do you think, does it seems raisonnable to revert this PR ?

Thanks in advance :)

**Comment by xavier-rodet** [comment]
Nevermind,

It seems that your documentation is in adequation with `@NotBlank(allowNull=true)` behaviour...

This means that setting a field to `@NotBlank(allowNull=true)` is not "required" in the playload by Symfony Validator!

My bad !
