### ISSUE TITLE
many classes with one abstract CRUD class - Annotations inheritance or dynamic @Model's

### ISSUE THREAD

**Issue by patrickbussmann** [nelmio/NelmioApiDocBundle#1652]
Hi everyone,

I read some topics but them are not clear enough for me.
#1610 #1406 #1473 #1550 

A very simple example.

My abstract controller.

```
abstract class CRUDBaseController extends BaseController
{
    const ENTITY_CLASS = '';

    /**
     * Creates item
     *
     * @SWG\Parameter(
     *     name = "Data",
     *     in = "body",
     *     type = "json",
     *     description = "The data for creation",
     *     required = true,
     *     @SWG\Schema(ref=@Model(type=this.getType()))
     * )
     * @SWG\Response(
     *     response = "200",
     *     description = "Returned when successful",
     *     @SWG\Schema(ref=@Model(type=static::ENTITY_CLASS))
     * )
     *
     * @Route("/test")
     */
	public function postEntity(Request $request, $item = null)
	{
		$data = $item ?: $this->createEntity();
		$form = $this->createForm($this->getType(), $data);
		$form->submit($request->request->all(), $item === null);
		if ($form->isSubmitted() && $form->isValid()) {
			$em = $this->getDoctrine()->getManager();
			$em->persist($data);
			$em->flush();
			return $data;
		}
		return $this->handleView($this->view($form->getErrors()));
	}

	abstract function getType(): string;
	abstract function createEntity();
	protected function securityQueryBuilder(QueryBuilder $queryBuilder, Request $request) { }
}
```

And then I'm overwriting it easily.

```
/**
 * @Route("/api/categories")
 */
class CategoryController extends CRUDBaseController
{
	const ENTITY_CLASS = Category::class;

	function getType(): string
	{
		return CategoryType::class;
	}

	function createEntity()
	{
		return new Category();
	}
}
```

This is working very well and easy.

But... The documentation is bad because `@Model(type=this.getType())` and `@Model(type=static::ENTITY_CLASS)` are not working.

When it'll work then I have easy generated documentation as well 🥳
But now I dont have 😌

Some ideas? 😊

**Comment by GuilhemN** [comment]
> But... The documentation is bad because @Model(type=this.getType()) and @Model(type=static::ENTITY_CLASS) are not working.

Well this is up to Doctrine annotations to support these annotations, but it would be very complicated since `\ReflectionMethod` does only point to the declaring class...

In my opinion the cleanest way to achieve this is to register a route describer (https://github.com/nelmio/NelmioApiDocBundle/blob/3.x/RouteDescriber/RouteDescriberInterface.php), extract the controller used from the `Route`, and if it is a subclass of `CRUDBaseController` call the model registry (https://github.com/nelmio/NelmioApiDocBundle/blob/master/Model/ModelRegistry.php, method `register`).
If you want to give this a try, please check the config files of this bundle to see examples of how to inject the model registry and how to register route describer, I won't have time to be much more explicit unfortunately.

**Comment by GuilhemN** [comment]
I'm closing this as I provided a solution, feel free to reopen if you have additional questions.
