### ISSUE TITLE
UI / resource assets not working after upgrading to Symfony 5

### ISSUE THREAD

**Issue by psociety** [nelmio/NelmioApiDocBundle#1675]
**Symfony version**: 5.0.*
**Nelmio version**: ^3.6

After upgrading to Symfony 5,  `symfony/web-server-bundle` package got deleted because it's deprecated and now all assets return the following error:
`No route found for "GET /bundles/nelmioapidoc/swagger-ui/swagger-ui.css"`.

I didn't see any any documentation note about this so i guess i'm missing something :S
I didn't upgrade nelmio from 2 to 3, i've always had 3.

**Comment by GuilhemN** [comment]
Have you tried running the command described [here][https://symfony.com/doc/current/bundles/NelmioApiDocBundle/faq.html#asset-files-not-loaded)?

**Comment by psociety** [comment]
Yes, it a shows success message, but still doesn't work. I mean i can see the files in public folder and everything, but it still fails to load them:
 --- -------------------- ------------------ 
      Bundle               Method / Error    
 --- -------------------- ------------------ 
  ✔   NelmioApiDocBundle   absolute symlink  
 --- -------------------- ------------------

**Comment by chrisguitarguy** [comment]
THis is probably happening because the PHP dev server is running with a router script versus directory. SEe https://www.php.net/manual/en/features.commandline.webserver.php

Eg `php -S localhost:9090 public/index.php` versus `php -S localhost:9090 -t public/`

You'll need to point PHP at a directory to make the assets work, but when you do that the `openapi.json` or `openapi.yml` routes will likely not work since PHP will think you want a file.

I've had to deal with this a few times and it honestly is not fun, but nothign this bundle can do about it unfortunately.
