### ISSUE TITLE
Unable to merge class Route annotation methods.

### ISSUE THREAD

**Issue by omrqs** [nelmio/NelmioApiDocBundle#1693]
Working on symfony 4.4, the annotation @Route can used on class or method scope. An option of @Route is 'methods', when it can simple value or array ("POST" or {"POST"} - for example.
If adding this annotation on class and method, these methods will merged.
The bug happen when on class @Route is used 'methods' and on method is used another methods. The symfony will use booth methods for this endpoint, but the NelmioBundle is showing the error: "User Notice: Unable to merge @SWG\Options()".

# Examples

## Success:
![image](https://user-images.githubusercontent.com/1513178/88688259-836d2f80-d0cf-11ea-9218-f8ab608cef6c.png)

### Symfony debug route:
![image](https://user-images.githubusercontent.com/1513178/88688398-a861a280-d0cf-11ea-9f07-e28127eb0ba5.png)

### API doc generated:
![image](https://user-images.githubusercontent.com/1513178/88688506-cb8c5200-d0cf-11ea-9578-fa4133cfeb35.png)

## Failure:
![image](https://user-images.githubusercontent.com/1513178/88688617-ebbc1100-d0cf-11ea-81d6-2a923a2942b2.png)
![image](https://user-images.githubusercontent.com/1513178/88688649-f676a600-d0cf-11ea-83d7-04c2aec22dc9.png)

### Symfony debug route:
![image](https://user-images.githubusercontent.com/1513178/88688777-16a66500-d0d0-11ea-9450-85005c282dda.png)

### API doc error:
![image](https://user-images.githubusercontent.com/1513178/88688858-2aea6200-d0d0-11ea-9617-33fa5072cba8.png)

**Comment by GuilhemN** [comment]
This is not something easy to fix as the 3.x version doesn't deal much with swagger php internals and the issue here is that you have two routes with the same path + method which can't be detected by the 3.x version.
Version 4 is able to deal with this by considering the two actions are just one but I believe there is a configuration issue on your behalf as you have two routes dealing with the same path + method.
Symfony solves this conflict using the routes definition order but this bundle does not have such a policy.

**Comment by omrqs** [comment]
Waitting feature for future releases.
