### ISSUE TITLE
Tag another beta ? Plan for release ? Milestone maybe ?

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#1702]
Hi,

I have been testing the beta 1 and had some trouble with some models that were not displayed in swagger ui.

This problem is not present in master.

Maybe a new beta can be tagged. 

Are there any blockers for a release? Maybe add a milestone to tag the issues?

Thanks for the awesome work!

**Comment by GuilhemN** [comment]
Hi! 

You're right I will tag a new beta today, I delayed this release because the development of 4.x is still quite active (see https://github.com/nelmio/NelmioApiDocBundle/compare/v4.0.0-BETA1...master) and we are still getting bug reports.
But releasing a first set of bug fixes should make this version more usable and avoid duplicated bug reports :smiley: 

> Thanks for the awesome work!

Thanks :heart: This version is an impressive team work, done brick by brick :)

**Comment by GuilhemN** [comment]
And it's done: https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.0.0-BETA2 :)
