### ISSUE TITLE
Unexpected token at the swagger ui bundle?

### ISSUE THREAD

**Issue by saninshakya** [nelmio/NelmioApiDocBundle#1719]
I have installed a `NelmioApiDocBundle ~ 3.7`. 

It works perfectly in my local. But in the server I am getting `Uncaught SyntaxError: Unexpected token '<'.`

This errors are pointed at

[swagger-ui-bundle.js:1 
swagger-ui-standalone-preset.js:1 
init-swagger-ui.js:1](url)
I am not sure how to fix this error.

Can anybody please help me on this.

**Comment by rishirajpurohit** [comment]
@saninshakya Would it be possible to take a look at the server url, where you see the error ?

**Comment by saninshakya** [comment]
> @saninshakya Would it be possible to take a look at the server url, where you see the error ?



> @saninshakya Would it be possible to take a look at the server url, where you see the error ?

**Comment by chrisguitarguy** [comment]
Without more details here, we can't help more. If I had to guess, something was happenign when generating the documentation so that SyntaxError thing was happening [here](https://github.com/nelmio/NelmioApiDocBundle/blob/0b82eb78c1953b5baa617b1bffe5dc0cd1286311/Resources/views/SwaggerUi/index.html.twig#L23). Maybe.

Going to close this for now, due to age, lack of details, and the v3.7 usage.
