### ISSUE TITLE
Fix Symfony\Component\PropertyInfo\Type::getCollectionKeyType() deprecation notice in symfony 5.3

### ISSUE THREAD

**Issue by FarhadKh** [nelmio/NelmioApiDocBundle#1877]
I get this deprecation notice
Since symfony/property-info 5.3: The "Symfony\Component\PropertyInfo\Type::getCollectionKeyType()" method is deprecated, use "getCollectionKeyTypes()" instead.

The deprecated method is called in these files:
ObjectPropertyDescriber

**Comment by bondarenkoid** [comment]
I have the same problem but with getCollectionVelueType():
Since symfony/property-info 5.3: The "Symfony\Component\PropertyInfo\Type::getCollectionValueType()" method is deprecated, use "getCollectionValueTypes()" instead

files called deprecated method ObjectPropertyDescriber / ArrayPropertyDescriber

**Comment by GuilhemN** [comment]
Fixed in #1888
