### ISSUE TITLE
OpenAPI 3.1.0 causes IntelliJ IDEA to leak memory (IDEA-280352) - example workaround for **temporary** usage in your own downstream projects 

### ISSUE THREAD

**Issue by Ocramius** [nelmio/NelmioApiDocBundle#1943]
Similar to #1940, I had to downgrade to OpenAPI 3.0.0 in my code.

In my case, it's because of https://youtrack.jetbrains.com/issue/IDEA-280352 - PHPStorm goes out of memory when attempting to load  an OpenAPI 3.1.0 schema.

I did not want to downgrade to `zircote/swagger-php:4.0.5` or `nelmio/api-doc-bundle:4.7.0`, so I decided to:

 1. keep all the benefits of the newer packages
 2. implement a stopgap solution (for now), waiting for the upstream IntelliJ IDEA issue to be fixed

Here's that "solution", but please beware that it's just something for temporary use, and I take no responsibility for any readers that don't make a plan for removing it once https://youtrack.jetbrains.com/issue/IDEA-280352 is solved.

<details>
<summary>Expand at the risk of burning your own retina</summary>

```php
<?php

declare(strict_types=1);

namespace Core\Adapter;

use Nelmio\ApiDocBundle\Describer\ModelRegistryAwareInterface;
use Nelmio\ApiDocBundle\Model\Model;
use Nelmio\ApiDocBundle\Model\ModelRegistry;
use Nelmio\ApiDocBundle\ModelDescriber\ModelDescriberInterface;
use OpenApi\Annotations\OpenApi;
use OpenApi\Annotations\Schema;
use Psl\Type;
use ReflectionProperty;

/**
 * @TODO drop this once https://youtrack.jetbrains.com/issue/IDEA-280352 is fixed in upstream PHPStorm
 *
 * @psalm-suppress UnusedClass
 */
final class RevertToOpenAPI3Describer implements ModelDescriberInterface, ModelRegistryAwareInterface
{
    /**
     * {@inheritDoc}
     *
     * Empty on purpose - this describer only modifies the ModelRegistry.
     * Interface implementation is still needed though, or else this describer will never be populated with
     * the registry.
     */
    public function describe(Model $model, Schema $schema): void
    {
    }

    public function supports(Model $model): bool
    {
        return false;
    }

    public function setModelRegistry(ModelRegistry $modelRegistry): void
    {
        Type\object(OpenApi::class)->coerce(
            (new ReflectionProperty($modelRegistry, 'api'))
                ->getValue($modelRegistry)
        )->openapi = '3.0.0';
    }
}

```

In your `services.yml` (yes, I happen to use the YAML version on my project):

```yml
    Core\Adapter\RevertToOpenAPI3Describer:
        tags: [ 'nelmio_api_doc.model_describer' ]
```
</details>

**Comment by spajxo** [comment]
Hi, might be helpful for some that openapi version can be downgraded also in bundle config like this
```
# config/package/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        openapi: '3.0.0'
```

**Comment by Ocramius** [comment]
That is certainly a much simpler/cleaner approach, thanks :D

**Comment by GuilhemN** [comment]
Thank you for reporting this issue!

I assume PHPStorm has some integrations with NelmioApiDocBundle for this to happen. Do you know more about this?

At first sight I would say I don't think it's the role of NelmioApiDocBundle to fix this (unless we have a way to specifically detect PHPStorm) as we would otherwise then be stucked with 3.0.0 for backwards compatibility but at the same time there's also swagger-ui that broke... (see https://github.com/nelmio/NelmioApiDocBundle/issues/1940) so we definitively have to do something.

In my opinion the correct solution would be to revert the `DEFAULT_VERSION` to `3.0.0` in `zircote/swagger-php` as the ecosystem is not mature enough to do the change seamlessly but I don't have no say on this. I suggested the idea to the maintainer of `zircote/swagger-php` in https://github.com/nelmio/NelmioApiDocBundle/issues/1940#issuecomment-1005796762 and will open an issue on their repository. If they don't want such revert we will enforce back `3.0.0` in NelmioApiDocBundle itself but I'm not very happy with that solution :/

**Comment by Ocramius** [comment]
@GuilhemN this is not a bug report: it's a pointer for others that may be stuck with this problem in IntelliJ.

It can be closed here, as there's no action to be taken by @nelmio maintainers.

**Comment by GuilhemN** [comment]
This is a side effect but it should be "fixed" by latest release of zircote/swagger-php https://github.com/zircote/swagger-php/releases.

PHPStorm will still need to do something should we change the default version back to 3.1 in NelmioApiDocBundle but we'll wait at least until Swagger-UI supports it. I'm closing this as we indeed cannot do much for this from this bundle.
