### ISSUE TITLE
Missing margins around the arrows

### ISSUE THREAD

**Issue by vimar** [nelmio/NelmioApiDocBundle#1958]
After upgrading to Nelmio 4. I see new arrows to each endpoint:

![image](https://user-images.githubusercontent.com/541354/152240672-e0139e78-cb42-4433-a2f3-848a4d121a2f.png)

It would be nice to add some margin around them to ensure they are all aligned (and not stick to border).

The CSS file I found is minimified, should I update it only? or I need to edit some other files?

**Comment by GuilhemN** [comment]
We are using Swagger UI and are not maintaining CSS files. This may have appeared in one of the recent releases, and an upgrade of Swagger-UI may solve the problem.

Could you try executing https://github.com/nelmio/NelmioApiDocBundle/blob/master/update-js.sh from the root of NelmioApiDocBundle, then resync the assets and check if it solves your issue?
Otherwise you may need to open an issue directly on https://github.com/swagger-api/swagger-ui

**Comment by GuilhemN** [comment]
Closing as I don't think this is an issue with this bundle but rather with SwaggerUI.
