### ISSUE TITLE
Memory Leak on v4.10

### ISSUE THREAD

**Issue by grimgit** [nelmio/NelmioApiDocBundle#2040]
Hi,
I've updated the bundle from version 4.9 to 4.10 and now the memory usage for the doc page is about 500MB (instead of ~100MB) and most of the time the 512MB memory limit is reached.

Rolling back to v4.9 fix the issue.

**Comment by GuilhemN** [comment]
I would assume this has been introduced by https://github.com/nelmio/NelmioApiDocBundle/commit/be8499ffdc5915c5af5e0d1d98071202fc1a5b94...
We tried to comply more with Swagger-PHP internals but that comes with more object loop references, and PHP garbage collector probably has a lot of difficulties cleaning those.

Could you check if this commit is indeed the cause of the memory leak you notice please? (by checking this commit and its parent)

Not sure how we should solve that if this is the root cause though...

**Comment by GuilhemN** [comment]
Thank you for confirming, I tried to look into memory consumption yesterday and a lot of it seems to come from annotations caching.

My guess is that the whole open API annotation is cached for every annotation loaded (so n² memory complexity it that's right 😅). 
I'll try to use the uncached annotations loader when I have a moment. I think we should rather cache at the end of the computation of the API, that should be more efficient.

**Comment by BafS** [comment]
Thanks for the report, we have the same issue since the last minor (4.10)

**Comment by GuilhemN** [comment]
I tried to come up with a solution but couldn't find a good one so far, so I think we should just revert the commit that introduced the regression for now, see https://github.com/nelmio/NelmioApiDocBundle/pull/2043.

**Comment by GuilhemN** [comment]
I reverted the commit involved and released a new patch.
So we should be good here, thank you for the report!
