### ISSUE TITLE
Indirect deprecations due to zircote/swagger-php 4.5.0

### ISSUE THREAD

**Issue by schodemeiss** [nelmio/NelmioApiDocBundle#2050]
Masses of indirect deprecations about Context::detect() from zircote/swagger-php.

This has been raised in an issue upstream (https://github.com/zircote/swagger-php/issues/1339) but as they point out, perhaps the issue is with this bundle.

**Comment by DerManoMann** [comment]
I suspect this is the result of rolling back #2043 . 
I am not convinced the issue was the number of objects created, since swagger-php will fall back to creating a new Context via the deprecated detect method.
Surly something to investigate. If this becomes too much of an issue we could perhaps turn off the deprecated message, but then I wonder how other projects do this

**Comment by GuilhemN** [comment]
Thank you for the report!

I tried to fix that issue in https://github.com/nelmio/NelmioApiDocBundle/pull/2053 (and also sort of reintroduce the changes reverted in #2043).

But I think it is problematic to throw a deprecation in this method as doctrine annotations instanciate all annotations they find on a method/class/property. So any code retrieving annotations where there is a Swagger-PHP annotation will trigger the deprecation. I think most apps don't see them only because the annotations loader is cached and the deprecations are thus triggered only on the first run.
This should be fixed with PHP attributes though as third party apps should not instanciate Swagger-PHP attributes out of context.

If the goal is ultimately to throw an exception when the context is not explicitly given, this will likely break a lot of apps (because of how doctrine annotations are retrieved).
