### ISSUE TITLE
Property type 'array' is deprecated what shold I use instead?

### ISSUE THREAD

**Issue by rizhenkov** [nelmio/NelmioApiDocBundle#2065]
It's a pretty hard to document my API. I think we need more examples with PHP Attributes.
In my case I don't know how to describe an input Dto with array parameters, described at another Dto. 

I tried to use Property type array, but it is marked as "deprecated" and not clear what I should to use instead:
```php
use OpenApi\Attributes as OA;
use Nelmio\ApiDocBundle\Annotation as NOA;

class CreateRefundDto
{

#[OA\Property(
    description: 'Refund rows',
    type: ̶a̶r̶r̶a̶y̶,
    items: new OA\Items(
        ref: new NOA\Model(
            type: CreateRefundRowDto::class
        ),
    ),
)]
```

<img width="582" alt="Снимок экрана 2023-01-06 в 17 00 24" src="https://user-images.githubusercontent.com/987517/211049774-73b9800a-c4d3-4caa-93ec-4244e8df1376.png">

When I change type "array" to something else I've got an error: 
`User Warning: @OA\Items() parent type must be "array" in \App\Core\DataEntity\RefundInput->rows in`

<img width="1142" alt="Снимок экрана 2023-01-06 в 19 17 25" src="https://user-images.githubusercontent.com/987517/211074071-c6a51775-59e8-4880-8c51-17d6a224f31f.png">

Update: This is a PHPStorm's bug. See [reply below](https://github.com/nelmio/NelmioApiDocBundle/issues/2065#issuecomment-1466535468)

**Comment by GuilhemN** [comment]
Do you have a trace for where this warning come from? I'm not able to find it in zircote/swagger-php codebase.
Which version of zircote/swagger-php are you using?

I don't really see why this would be deprecated, may be an issue with your IDE.

**Comment by rizhenkov** [comment]
1. @GuilhemN this warning shows only when I try to replace "array" type for something else and maybe it is not an error. 

<details>
  <summary>Warning source trace</summary>
  <img width="1027" alt="image" src="https://user-images.githubusercontent.com/987517/211265551-3e4ec315-52c1-4742-a98e-956006d9a67b.png">
</details>

2. I am using the nelmio/api-doc-bundle": "^4.10 (currently v4.10.2). 
It is uses "zircote/swagger-php": "^4.2.15" (currently 4.5.2)

3. Maybe it's an issue with IDE, but this IDE is a very popular (PhpStorm 2022.3.1), I think this case can be solved some way. 
Especially when there is no suchlike bugs with other attributes and types.

**Comment by GuilhemN** [comment]
Sorry for the confusion, the zircote/swagger-php warning is valid. The type in your `OA\Property` has to be array.

What I don't understand is why PhpStorm reports `Deprecated: Use {@link JsonType} instead`. But I think you should rather open an issue on https://github.com/zircote/swagger-php if this persists, we don't have any control on their attributes/annotations.
This deprecation might also be caused by some other library that deprecated a constant string with value `array`?

**Comment by jgauthi** [comment]
The message comes from the ORM doctrine side attribute which has deprecated `array` type fields.

**Comment by kevinpapst** [comment]
Just in case someone else stumbles upon it:
<img width="944" alt="Bildschirm­foto 2023-03-13 um 17 56 36" src="https://user-images.githubusercontent.com/533162/224771826-a923ed66-4047-4b48-804e-89680faa8148.png">

Unfortunately disabling this will stop warning about other Doctrine issues as well:
<img width="1075" alt="Bildschirm­foto 2023-03-13 um 17 58 31" src="https://user-images.githubusercontent.com/533162/224772312-39d2c4eb-33f1-440b-bd7d-8e9d321826a3.png">

Annoying problem, I don't understand why PHPStorm blindly marks attribute parameters, instead of checking their type.

**Comment by rizhenkov** [comment]
Thank you, @kevinpapst. This setting helps. 

This bug is totally on the PHPStorm's side, any chances to somehow report it to them?

**Comment by djmarland** [comment]
> Thank you, @kevinpapst. This setting helps.
> 
> This bug is totally on the PHPStorm's side, any chances to somehow report it to them?

Bugs can be reported at https://youtrack.jetbrains.com/issues
I was about to raise it but I don't have a set of steps to reproduce. It _sounds_ like its a combination of using Doctrine and OpenAPI, and PHPStorm is matching to the wrong source Attribute to decide deprecation.
