### ISSUE TITLE
Readonly Properties with equal name in constructor parameter leads to invalid attribute class in Response

### ISSUE THREAD

**Issue by superkozel** [nelmio/NelmioApiDocBundle#2069]
```
class SomeResponse
{
    public readonly ModelListResponse $models;

    public function __construct(
        ModelList $models,
    ) {
        $this->models = new ModelListResponse(models);
    }
}
```

with this code for some reason you get wrong Class for SomeResponse.models, ModelList instead of ModelListResponse, maybe model analyzer thinks that there is property promotion and prioritizes constructor class.

**Comment by GuilhemN** [comment]
This is due to `symfony/property-info` behavior (https://github.com/symfony/symfony/blob/1f7bc1098f0b03181095d35b11fa48523864e6f2/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L136-L158), it tries to resolve type in the following order:
- mutator
- accessor
- constructor argument
- property

So constructor type takes over your property type.
Not sure what we could do here... I guess the two could be exchanged but that's rather a discussion to have on the Symfony repository.

**Comment by GuilhemN** [comment]
Closing as there's not much we can do here I think.
