### ISSUE TITLE
Properties with default values still get marked as required

### ISSUE THREAD

**Issue by janikfu** [nelmio/NelmioApiDocBundle#2222]
Since v4.15.0, we've encountered a problem regarding non-required properties
A property gets initialized in the constructor with a default value:
```php
    public function __construct(
        #[Groups('docs')]
        #[Valid]
        private readonly CompanyQueryFilters $filters = new CompanyQueryFilters()
    ) {
    }
```
```php
final readonly class CompanyQueryFilters {
    public function __construct(
        #[Groups('docs')]
        private ?string $organisation = null
    ) {
    }

    public function getOrganisation(): ?string {
        return $this->organisation;
    }
}
```

The schema output is as follows:
```json
    "GetAllCompaniesQuery": {
        "required": [
            "filters"
        ],
        "properties": {
            "filters": {
                "$ref": "#/components/schemas/CompanyQueryFilters"
            }
        },
        "type": "object"
    },
```

We expect the `filters`-property to be non-required.

Follow-up on #2185 and #2179

**Comment by CatalinH** [comment]
Hi all
First of, thank you for the support with this package.

It might be that in version 4.25, among changes that fixed the default values being marked as required, that default values now take precedence in the generated example instead of continuing to parse the model.

https://github.com/nelmio/NelmioApiDocBundle/pull/2248/files#diff-ac3630f337572925e1525239a4ae887c7db2ca259f49b43eadb296ee7ffa8695R162

Sorry about the poor description, I'm really bad with markdown, but I'll try to explain the context a bit:

Action file has response description as follows:
`    #[OAResponse(
        response: Response::HTTP_OK,
        description: 'Objects list',
        content: new JsonContent(
            properties: [
                new Property(property: 'code', type: 'integer', enum: [Response::HTTP_OK]),
                new Property(property: 'data', ref: new Model(type: ListResponse::class), type: 'object'),
            ]
        )
    )]
`

ListResponse class containa 1 property, a list, which has default value to empty array
`
#[Schema(required: ['subItems'])]
class ListResponse
{
    /**
     * @var SubResponseElement[] $subItems
     */
    #[Property(
        description: 'Sub elements',
        type: 'array',
        items: new Items(ref: new Model(type: SubResponseElement::class))
    )]
    protected array $subItems = [];
`

SubResponseElement has 2 properties, each with example value
`
    #[Property(
        description: 'Identifier',
        type: 'integer',
        example: 1
    )]
    protected int $id;

    #[Property(
        description: 'Property Name',
        type: 'string',
        maxLength: 255,
        minLength: 1,
        example: 'Random Name'
    )]
    protected string $name;
`

Prior to version 4.25, the computed json for ListResponse was as follows:
`
            "ListResponse": {
                "required": [
                    "subItems"
                ],
                "properties": {
                    "subItems": {
                        "description": "Sub elements",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/SubResponseElement"
                        }
                    }
                },
                "type": "object"
            },
`
Starting with 4.25 it is as follows
`
            "ListResponse": {
                "required": [
                    "subItems"
                ],
                "properties": {
                    "subItems": {
                        "description": "Sub elements",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/SubResponseElement"
                        },
                        "default": []
                    }
                },
                "type": "object"
            },
`
As per my understanding of the details in  https://swagger.io/docs/specification/describing-parameters/#mistakes , default parameter should not be used in conjunction with required and there might be other cases when parsing the chained models would be better to compute the example in swagger ui.

Example yaml
`
openapi: 3.0.0
info:
  title: Example Api
  description: Example api
  version: undefined
paths:
  /api/list:
    get:
      summary: List all 
      operationId: list
      responses:
        '200':
          description: List example
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    enum:
                      - 200
                  data:
                    $ref: '#/components/schemas/ListResponse'
                type: object
components:
  schemas:
    ListResponse:
      required:
        - subItems
      properties:
        subItems:
          description: Sub items
          type: array
          items:
            $ref: '#/components/schemas/ResponseElement'
          default: []
      type: object
    ResponseElement:
      properties:
        id:
          description: identifier
          type: integer
          example: 1
        name:
          description: Name
          type: string
          maxLength: 255
          minLength: 1
          example: Example Name
      type: object
`

Unexpected:
![image](https://github.com/user-attachments/assets/12182ccc-6881-4a56-957a-7b02bfacb4c4)

Expected:
![image](https://github.com/user-attachments/assets/fc777c14-d78c-4a48-b26a-1b70b1967ce6)

Schema is still rendered correctly:
![image](https://github.com/user-attachments/assets/276cc66f-fc55-440c-af69-d21a028e9640)

Looking for some guidance related to this issue

**Comment by DjordyKoert** [comment]
@CatalinH 
> As per my understanding of the details in https://swagger.io/docs/specification/describing-parameters/#mistakes , default parameter should not be used in conjunction with required

Could you create a new issue for this? I didn't know that using these in conjunction was a mistake. 😃 

> would be better to compute the example in swagger ui.

I don't think I can help with the issue your are seeing inside of [Swagger UI](https://github.com/swagger-api/swagger-ui). Swagger UI apparently prefers to show the `default` in the "Example value" field and this behavior lies entirely inside of that project.

**Comment by CatalinH** [comment]
Hey
Thanks for the quick response. Now that you've mentioned, indeed it sounds as something that should be fixed in the UI
I will try to open a new issue in the next few days
