### ISSUE TITLE
[Bug]: Bad generated json (or clients?) since upgrade from 4.12

### ISSUE THREAD

**Issue by etshy** [nelmio/NelmioApiDocBundle#2326]
### Version

4.29

### Description

After upgrading from 4.12 to 4.29, The generated clients (using openapi-generator 7.1) have changed their class names.
Main changes between both version with our code is the `allOf` changed to `oneOf` (so related to #2156 ?).

I'm not sure the problem lies on the bundle generating the json or on `openapi-generator` changing the way it's generating classname depending on `oneOf` or `allOf`, But I'm making this issue to have a trace of the problem. (the reference names are the same in both version json)
And I want to make sure the probleme isn't from here.

Also, maybe changing the way the json is generated shouldn't have been a minor version update ?

### JSON OpenApi

Not much to show, especially on proprietary code, the only thing is that all `allOf` changed to `oneOf`

**Comment by DjordyKoert** [comment]
> The generated clients (using openapi-generator 7.1) have changed their class names.
Main changes between both version with our code is the allOf changed to oneOf (so related to https://github.com/nelmio/NelmioApiDocBundle/pull/2156 ?).

The change is most likely related to https://github.com/nelmio/NelmioApiDocBundle/pull/2156, but the change in class names is an issue on openapi-generator because they apparently generate a classname by depending on `oneOf` / `allOf`

> Also, maybe changing the way the json is generated shouldn't have been a minor version update ?

That would mean a major would need to be replaced whenever _anything_ changes about the json, this is not a breaking change :)

**Comment by etshy** [comment]
> That would mean a major would need to be replaced whenever anything changes about the json, this is not a breaking change :)

Yeah that's true, though upgrading a minor completely changing our clients was surprising.

I added a comment on an existing issue about `oneOf` here : OpenAPITools/openapi-generator#2011

It's an old issue but still hope someone will take a look at it

Thanks for the clirification I'll close this issue.
