### ISSUE TITLE
@QueryParam, array=true with default={"id"="asc"} throws a 500 error 

### ISSUE THREAD

**Issue by leevigraham** [nelmio/NelmioApiDocBundle#401]
Adding the following annotation:

```
* @QueryParam(name="orderBy", array=true, default={"id"="asc"})
```

results in an exception and a 500 error:

[Wed Jun 04 22:17:48 2014] [error] [client 127.0.0.1] PHP  29. Symfony\Component\Debug\Exception\FlattenException->flattenArgs($args = _uninitialized_, $level = _uninitialized_) /Users/leevigraham/Sites/Personal/Symfony2/standard/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/FlattenException.php:223

However removing `default={"id"="asc"}` outputs the docs. I'm trying to nail down the issue but it seems that the docs cannot render an array representation.

**Comment by solazs** [comment]
This issue is present again with symfony 2.6:

@Annotations\QueryParam(name="tags", array=true, default={}, description="Tags to filter the query")

CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in "NelmioApiDocBundle::method.html.twig" at line 223." at /home/baloo/hexaa/vendor/twig/twig/lib/Twig/Template.php line 304 

I'm trying to set the default to an empty array.
