### ISSUE TITLE
Sandbox - LINK is sent via POST with _method parameter (UNLINK is not)

### ISSUE THREAD

**Issue by JakubFojtik** [nelmio/NelmioApiDocBundle#621]
Sending a LINK request is done via [method faking](http://symfony.com/doc/current/cookbook/routing/method_parameters.html#faking-the-method-with-method), so it sends a POST.
I believe it is a bug, since UNLINK and other methods are used directly.
Also, since LINKing is used on a non-collection resource like /something/1, the POST method would be disabled on it and a '405 Method Not Allowed' error is thrown.

If it is because of the [firefox bug](http://stackoverflow.com/questions/9649972/firefox-overwrites-custom-http-method-link-to-mixed-case-link-on-xhr), that one seems to be [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=477578) already.

**Comment by willdurand** [comment]
Yes, that's because of Firefox's bug. Should we change this behavior now? Willing to work on it?

**Comment by tonivdv** [comment]
Hello @willdurand ,

I've got this issue with Google Chrome as well ...

The lines causing the issue is in the file "layout.html.twig" starting at line 524

```php
// Workaround for Firefox bug and a thereby resulting nginx incompatibility
if (method == "LINK") {
  method = "POST";
  params._method = "LINK";
}
```

Fix from https://github.com/nelmio/NelmioApiDocBundle/commit/4fa50ebe5339674bdad2fcf94f288ba63a7b1def

Reverting this works on Chrome. If it's a firefox workaround, maybe it should only be executed when it's a firefox browser?

Let me know your thoughts, and I can PR if needed.

Cheers

**Comment by willdurand** [comment]
Let's apply this fix only on Firefox then :)

**Comment by tonivdv** [comment]
@willdurand Will do ;)

**Comment by tonivdv** [comment]
@willdurand I just checked with firefox ... it fails too ... so I guess we can simply remove it? /cc @JakubFojtik

**Comment by willdurand** [comment]
@tonivdv ok then

**Comment by foaly-nr1** [comment]
Any progress on this? :+1:

**Comment by tonivdv** [comment]
@foaly-nr1 Well I PR a change, but it made test fail however I don't get why they failed.
