### ISSUE TITLE
How to document returned HTTP headers?

### ISSUE THREAD

**Issue by felicitus** [nelmio/NelmioApiDocBundle#631]
In my API, I support pagination and I want to return the total number of records via a HTTP header. How would I document returned HTTP headers using this bundle?

**Comment by willdurand** [comment]
Interesting question, by now you probably can't, except by writing the doc in the action's doc block.

**Comment by bjoernHeneka** [comment]
Would be also interested in a way how to handle that.

**Comment by dbu** [comment]
apart from the general description there is nothing i think. version 3 is a complete rewrite and uses swagger-php for annotations. maybe check if they support it and if they do but the nelmio bundle does not support it, send us a pull request. otherwise send them a pull request. (if swagger even supports header specifications)
