### ISSUE TITLE
All tests fails because of Symfony 2.7 deprecation notice

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#636]
Hi,

Since symfony 2.7 have been released, all tests are failing because of deprecation notices.

**Comment by willdurand** [comment]
Right. Would you mind fix the test suite?

**Comment by magnetik** [comment]
It seems that #614 is on its way to fix this. I'll try to help on that.

**Comment by magnetik** [comment]
Looks like it's okay now since the tests of #637 are passing.

**Comment by skonsoft** [comment]
Hello,

there is some deprecations are not fixed yet:

DEPRECATED - The "pattern" option in file "/var/www/dev/my_project/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead. 

DEPRECATED - The "_method" requirement of route "nelmio_api_doc_index" in file "/var/www/dev/my_project/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" option instead. 

Can you fix this please ?

Thank you !
