### ISSUE TITLE
QueryParam set symfony parameter has a default value 

### ISSUE THREAD

**Issue by antoinemineau** [nelmio/NelmioApiDocBundle#723]
Hello,

Is their a way to use a symfony parameter (defined in config/parameters.yml) as a default value such as : @Rest\QueryParam(name="version", description="Api Version number", default=%api_version%)

Didn't find a related issue and information in the doc.

**Comment by mRoca** [comment]
Hello, you can create a new Extractor handler (implementing the HandlerInterface) in order to do that : https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.md#using-your-own-annotations.
I've not tested, but I think you can use the `$annotation->getFilters()` method to get all yet declared methods and update the fields.
You can also create your own annotation and parse it.

**Comment by antoinemineau** [comment]
@mRoca 

Great !
Thanks for the advices, I will work on that.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
