### ISSUE TITLE
Validation config is ignored if class set us input is not in the same bundle as config file.

### ISSUE THREAD

**Issue by XanderEmu** [nelmio/NelmioApiDocBundle#728]
If you set something which is handled by Validation ApiDocBundle will handle it nicely and - in docs - you will see all input parameters based on validation config. That works great.

But if that class is not in the same bundle as validation config file then ApiDocBundle ignores it.

**Comment by fstr** [comment]
As far as I can see it's using the default Symfony LoaderChain to load the ClassMetaData with all available loaders. The YamlFilesLoader will then check for validation.yml files in all Bundles in case you refer to a validation.yml.

Since 2.7 probably also all files being in a validation/ subfolder.

Maybe you can give some more details for your problem.
