### ISSUE TITLE
Multiple versions with multiple views

### ISSUE THREAD

**Issue by JHGitty** [nelmio/NelmioApiDocBundle#754]
I want to have 2 views: `default` and `premium`.
I want to have 3 versions: `v1`, `v2` and `v3`.

In the documentation there is:
https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/multiple-api-doc.md#accessing-specific-api-views

The documentation explains about views but not how to handle multiple api versions.

Is there any good solution for this?

Should I create 6 views (2 views for each version) named for example `v1_default`, `v1_premium`, ..?

I think the documentation page should explain it better because the example URL contains "/v1/".
Another idea is to change the example URL to "http://api.example.com/doc/" without version.

**Comment by dkisselev** [comment]
I think creating 6 views would be the cleanest way to handle it,

The types/number of views may change across API versions (since API v2 doesn't owe v1 anything and can stand on its own), so it wouldn't make sense to make a global configuration or define for view types.

I totally agree on your point about the example though, I was just looking at that and noticed the same (confusing) thing.

Is it possible to add '/' to a view name and still have it route correctly? If not that might be an important fix so that doc URL's can stay more consistent with the real endpoints.

**Comment by jmaheux** [comment]
As of version 2.13.0, this is apparently not possible to have a "/" in a view name. I agree that this would be  a nice improvement.

**Comment by develth** [comment]
+1 - missing a version separation feature

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
