### ISSUE TITLE
Create a new release with fixes for "Avoid array to string conversion error" 

### ISSUE THREAD

**Issue by lmammino** [nelmio/NelmioApiDocBundle#770]
It would be great to have a new release with the fixes introduced [here](https://github.com/nelmio/NelmioApiDocBundle/commit/d3bc49c3d1d588aa7da699fbc36b2a836816e609).

I need it for a project on which we decided to not have dependencies tracked with "master"

**Comment by lmammino** [comment]
Hello @willdurand, is this closed because is rejected or because a release is going to be published any time soon? If you have a deadline for it, that would be great.

Thanks

**Comment by willdurand** [comment]
It is closed because it is not an issue per se :)

I do my best to release versions as often as possible, cf. [this page](https://github.com/nelmio/NelmioApiDocBundle/releases). Yet, I have many (popular) libs/bundles to maintain, cf. https://github.com/willdurand, and no much free time. I am writing my PhD thesis.

**Comment by lmammino** [comment]
Ok thanks for the clarification @willdurand. I'll keep an eye on the releases page.
Best of luck for your thesis :wink: I am sure you'll do a great job as much as you are doing with all your open source contributions!

**Comment by lmammino** [comment]
In case someone ends up here I just want to point out that this has been resolved with [2.11.2 Release](https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.11.2).

Thanks to @willdurand for the effort
