### ISSUE TITLE
Nelmio ApiDoc consumming too much memory

### ISSUE THREAD

**Issue by manuelbcd** [nelmio/NelmioApiDocBundle#931]
Hi, my application has a big ammount of Documents (ODM) and API's and I'm facing several problems with memory.

If I set any value below 256M in my PHP.ini the Doc throws a Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in /var/www/html/vendor/twig/twig/lib/Twig/Node/Module.php on line 149

I'm wondering if Nelmio API could be sliced in order to avoid this extreme effort.

Thanks in advance

**Comment by gornostal** [comment]
@manuelbcd have you found any workaround?

**Comment by manuelbcd** [comment]
Not yet @gornostal. We are still evaluating the best solution possible. I'm wondering if nobody faced the same problem since I think it would be normal in any big application.

**Comment by niniks** [comment]
@manuelbcd same problem here, i raised the memory to 1024 now and still it takes some time to generate the docs. Also scrolling through the docs is laggy, i need to say its not that strange because im loading around 150 controllers with multiple functions each.

Could it be an idea to introduce pagination in the api doc so it would be able to focus on chunks instead of the total, another thing could be a load more button instead of pagination but still deviding the data in chunks instead of loading it all at once.

**Comment by GuilhemN** [comment]
3.0 is a complete refactor, could you try if it works better for you?

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
