### ISSUE TITLE
[3.0] Support swagger tag

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#965]
Hi,

If I'm not wrong, it seems that that the tags are added to the swagger document, but not added on routes.

Seems like a good addition

**Comment by GuilhemN** [comment]
What do you mean?
You can add tags on routes using
```php
/**
 * @SWG\Get(
 *     tags={"foo", "bar"}
 * )
 */
public function myAction() {}
```

**Comment by magnetik** [comment]
Since I'm using FOSRestBundle, I was not adding `@SWG\Get`, but I was adding `@SWG\Tag` on my action directly. 
Obviously at the moment this does not work, but repeating the method to declare the tag feels wrong to me.

**Comment by GuilhemN** [comment]
@magnetik it doesn't seem to be meant for this so it would first require a PR on Swagger-php repo to support `@Tag` in `@Operation`.
But otherwise I like it :+1: maybe we'll be able to get ride of `@Operation`

**Comment by GuilhemN** [comment]
In fact, it is logical [according to the spec](http://swagger.io/specification/).
`Operation::$tags` is an array of strings while `Swagger::$tags` is an array of `Tag`, so I don't think we can change something here.

**Comment by magnetik** [comment]
Yeah so I have to redefine the method using `@SWG\Get` or `@SWG\Post`, not a big fan of this.

Don't we need our own annotation to define things like that?

I was also wondering about supporting view (as defined in the v2), does it make sense to you?

**Comment by GuilhemN** [comment]
> Yeah so I have to redefine the method using @SWG\Get or @SWG\Post, not a big fan of this.
me neither

> Don't we need our own annotation to define things like that?
We could make `@Tag` work at the root of methods only for this bundle, we already have a very different semantic than Swagger-Php anyway.

> I was also wondering about supporting view (as defined in the v2), does it make sense to you?
I'm not sure of the benefit, do you have an use case?

**Comment by daevidvincent** [comment]
As someone coming from the old nelmio, our code has a bazillion @ApiDoc blocks. We then attempted to use Swagger-PHP (since other teams in our company are using that) but Symfony puked on all the @SWG annotations. FWIW, I would love it if this new Nelmio could handle the same annotations as Swagger-PHP to make the 2.0 output JSON. I saw you mention the semantic is different and that concerns me. They should be compatible. It just makes life harder for everyone if there is yet another syntax to learn and it makes tools incompatible then (and proprietary). I say that if you go with the Swagger-PHP style then it should follow and be compatible with that. Otherwise stick to your @ApiDoc blocks and make them as compatible with the "old" nelmio syntax with new 2.0 swagger so we don't have to re-factor so much code or have two styles of annotations for everything (those things get HUGE! some comments are bigger than the actual methods by as much as two or three times!)

**Comment by GuilhemN** [comment]
@daevidvincent I understand your concern, when I say the semantic is different, I mean you can use something that is more adapted to symfony but the normal syntax will still work (to ease the migration).
For example these two doc blocks would be the same for nelmioapidocbundle:
```php
/**
 * @Route("/foo")
 * @SWG\Get(
 *    path="/foo",
 *    @Response(response="200", description="Success")
 * )
 */
public function myAction()
{
}

/**
 * @Route("/foo")
 * @Response(response="200", description="Success")
 */
public function myAction()
{
}
```

We're gonna have our own parser that will only parse controller's methods but I think people coming from Swagger-Php will also need to parse their entities so I think we'll add an option to parse these files separately.

**Comment by magnetik** [comment]
I've created a different issue about the views support: #974

**Comment by GuilhemN** [comment]
see https://github.com/nelmio/NelmioApiDocBundle/pull/975https://github.com/nelmio/NelmioApiDocBundle/pull/975
